version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: monthly
    target-branch: develop
    open-pull-requests-limit: 3
    groups:
      gradle-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: npm
    directory: /frontend/rockepilates-web
    schedule:
      interval: monthly
    target-branch: develop
    open-pull-requests-limit: 3
    groups:
      npm-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    target-branch: develop
    open-pull-requests-limit: 3
    groups:
      actions-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
