server:
  port: 8082

spring:
  application:
    name: gerenciador-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/gerenciador_db}
    username: ${DB_USERNAME:rocker}
    password: ${DB_PASSWORD:rocker123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

storage:
  provider: local
  local:
    upload-dir: uploads
    public-url-prefix: /uploads
  s3:
    bucket-name:
    region:
    access-key:
    secret-key:
    public-url-prefix:

management:
  endpoints:
    web:
      exposure:
        include: health